### DISCUSSION TITLE
guide/component-overrides/

### DISCUSSION THREAD

**Discussion by giscus** [pengzhanbo/vuepress-theme-plume#232] [docs-comment]
# guide/component-overrides/

概述 布局插槽十分实用，但有时候你可能会觉得它不够灵活。主题同样提供了单个组件覆写的能力。 注意 在使用此功能前，你应该首先熟悉本主题的源代码，了解 主题内置的各个组件，以便 安全的 覆写他们。 主题的组件源代码托管在 GitHub，遵循 MIT 协议。 使用 主题将所有 非全局的组件 都注册了一个带 @theme 前缀的 alias 。 例如，VPF...

https://theme-plume.vuejs.press/guide/component-overrides/

**Comment by MrHaoH** [comment]
您好，我请教个问题，我想用自己的组件覆盖主题内的头部组件，我在.vuepress/config.ts文件中配置了
    alias: {
        '@theme/VPNavbar.vue': path.resolve(
            __dirname,
            './components/MyNav.vue',
        ),
    },
为啥没有生效？感谢大佬的回复

**Reply by pengzhanbo** [reply]
组件别名是 `@theme/Nav/VPNavBar.vue`

**Reply by MrHaoH** [reply]
哦哦，我明白了，@theme后面跟的是路径是吧，并不单纯的是组件名，感谢大佬的回复

**Comment by MrHaoH** [comment]
大佬，如何把内置的404替换成自定义的？？
'@theme/layouts/NotFound.vue': path.resolve(
            __dirname,
            './components/div.vue',
        )
我这样写解析不出来，感谢感谢

**Reply by pengzhanbo** [reply]
`.vuepress/client.ts`
```ts
import { defineClientConfig } from 'vuepress/client'
import NotFound from './layouts/NotFound.vue'

export default defineClientConfig({
  layouts: {
    NotFound,
  },
})
```
`./layouts/NotFound.vue`
```vue
<script setup>
import { NotFound } from 'vuepress-theme-plume/client'
</script>

<template>
  <NotFound>
    <template #not-found>
      <div>
        自定义内容
      </div>
    </template>
  </NotFound>
</template>
```

**Reply by MrHaoH** [reply]
感谢大佬

**Comment by Jursin** [comment]
请问我想修改 VPPosts 组件样式部分的 .posts-container.no-profile 的 max-width，怎么修改，需要组件覆写吗

**Reply by pengzhanbo** [reply]
直接进行样式覆盖即可。

**Reply by Jursin** [reply]
我在 style/index.css 这样写

```css
.posts-container.no-profile {
    max-width: 850px;
}
```

但未生效

**Reply by pengzhanbo** [reply]
CSS 是有优先级的。最简单的方法就是加上 `!important`

**Reply by Jursin** [reply]
加上还是不变，查看页面元素：
```css
.posts-container.no-profile[data-v-43c89c1d] {
    display: block;
    max-width: 784px;
}

.posts-container.no-profile {
    max-width: 850px !important;
}
```
