### ISSUE TITLE
左侧菜单栏导航不显示

### ISSUE THREAD

**Issue by Thank4** [pengzhanbo/vuepress-theme-plume#164]
![QQ_1725445603288](https://github.com/user-attachments/assets/1727f1c6-c43c-4e1e-989b-e8bd9c8de581)

![QQ_1725445462683](https://github.com/user-attachments/assets/9d19edc5-e2bf-428a-a1e9-dad9502e8b37)

### config.js

```js
import { defineUserConfig } from 'vuepress/cli'
import { viteBundler } from '@vuepress/bundler-vite'
import {defineNoteConfig, plumeTheme} from "vuepress-theme-plume";




export default defineUserConfig({
  lang: 'zh-CN',

  title: '设计模式笔记',
  description: '记录学习设计模式笔记',
  theme: plumeTheme({
    notes: {
      dir: 'notes', // 声明所有笔记的目录
      link: '/', // 声明所有笔记默认的链接前缀， 默认为 '/'
      notes: [
        {
          dir: 'principle', // 声明笔记的目录，相对于 `notes.dir`
          link: '/principle/', // 声明笔记的链接前缀
          sidebar: [ // 配置侧边栏
            {
              text: '单一责任原则',
              icon: 'mdi:language-typescript', // 侧边栏图标
              items: ['SingleResponsibility'] // 简化写法，主题会自动补全为 `foo.md`
            },
            {
              text: '接口隔离原则',
              icon: 'mdi:language-typescript', // 侧边栏图标
              items: ['InterfaceSegregation'] // 简化写法，主题会自动补全为 `foo.md`
            }
          ]
        }
      ]
    }
  }),

  bundler: viteBundler(),
})

```

### package.json

```
{
  "name": "design-pattern",
  "version": "1.0.0",
  "description": "Notes on Learning Design Patterns",
  "license": "MIT",
  "type": "module",
  "scripts": {
    "docs:build": "vuepress build docs",
    "docs:clean-dev": "vuepress dev docs --clean-cache",
    "docs:dev": "vuepress dev docs",
    "docs:update-package": "pnpm dlx vp-update"
  },
  "devDependencies": {
    "@vuepress/bundler-vite": "2.0.0-rc.15",
    "@vuepress/theme-default": "^2.0.0-rc.11",
    "vue": "^3.4.0",
    "vuepress": "^2.0.0-rc.7",
    "vuepress-theme-plume": "1.0.0-rc.93"
  },
  "dependencies": {
    "@vuepress/plugin-prismjs": "2.0.0-rc.42"
  }
}

```

### README.md

```
---
pageLayout: home
externalLinkIcon: false
config:
  -
    type: hero
    full: true
    background: tint-plate
    hero:
      name: 设计模式
      tagline: Design Pattern
      text: 设计模式学习及总结
      actions:
        -
          theme: brand
          text: 快速开始 →
          link: /notes/principle/SingleResponsibility
        -
          theme: alt
          text: Github
          link: https://github.com/pengzhanbo/vuepress-theme-plume



```
